on: workflow_dispatch
  
name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("tidyverse"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: run Rscript
        run: Rscript "getdata.R"
      