name: ScaricaUltimi90Giorni

on: workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        R: [ '4.0.5' ]
        
    name: R ${{ matrix.R }} setup
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript "getdata.R"

