
on: workflow_dispatch

name: MyScript

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install Libraries
        run: Rscript -e 'install.packages("readr", "dplyr", "lubridate")'
      - name: Run getdata.R
        run: Rscript "getdata.R"


