
on: workflow_dispatch

name: MyScript

jobs:
  R-CMD-check:
<<<<<<< HEAD
  
    runs-on: macOS-latest
    
=======
    runs-on: windows-latest
>>>>>>> e5727ed623f5d226bbd25d8440ec9625dc6d7b9a
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    
      - uses: actions/checkout@v2
<<<<<<< HEAD
      
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
          
      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
        
        - name: Cache R packages
          uses: actions/cache@v1
          with:
            path: ${{ env.R_LIBS_USER }}
            key: macOS-r-4.0-2-${{ hashFiles('.github/depends.Rds') }}
            restore-keys: macOS-r-4.0-2-
            
      - name: Install dependencies
        run: |
          remotes::install_cran("tidyverse")
          remotes::install_cran("shiny")
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
          remotes::install_github("tidyverse/tidytemplate")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .
      
=======
      - uses: r-lib/actions/setup-r@v1
      - name: Install Libraries
        run: Rscript -e 'install.packages("readr", "dplyr", "lubridate")'
>>>>>>> e5727ed623f5d226bbd25d8440ec9625dc6d7b9a
      - name: Run getdata.R
        run: Rscript "getdata.R"


